### ISSUE TITLE
toggle-menu: sometimes the shortcut has to be pressed two times

### ISSUE THREAD

**Issue by ralf3u** [xiota/geanylua-scripts#1]
issue 1
When I restart the computer and I open Geany for the first time and if I press F12 nothing happens (my shortcut is F12 to toggle the menu-bar). Then after the second press of F12 it works fine, so the menu-bar appears and disappears after each press of F12.

issue 2
The same issue happens when the menu-bar is not there any more and then I close Geany. After a restart of Geany I need to press two times F12 to let disappear the menu-bar. Then the menu-bar appears and disappears after each press of F12.

Geany 1.37.1, Lubuntu 21.04

**Comment by xiota** [comment]
In response to your question about [running GeanyLua commands from the terminal](https://github.com/geany/geany/issues/633#issuecomment-924804628), I don't think it's possible without modifying the GeanyLua plugin and possibly also Geany.

About having to press the shortcut twice, did you copy the files from the `events` folder to `.config/geany/plugins/geanylua/events`?

The script is does not currently save its state between restarts.  It would have to be modified to do so.

**Comment by xiota** [comment]
I've added instructions to [/events/init.lua](https://github.com/xiota/geanylua-scripts/blob/main/toggle-menu/events/init.lua) about how to start with the menu hidden.

**Comment by ralf3u** [comment]
> ..., did you copy the files from the events folder to ....

I can't find the events folder.

>I've added instructions to /events/init.lua about how to start with the menu hidden.

Should I put init.lua in .config/geany/plugins/geanylua/events/? I did that, but after a restart Geany has a problem.

**Comment by ralf3u** [comment]
If I put init.lua in .config/geany/plugins/geanylua/ then issue 2 does not occur any more.
But Geany does not start without menu-bar.  To start without menu-bar would be better.

**Comment by xiota** [comment]
What is the problem?

**Comment by xiota** [comment]
@ralf3u Can you describe the problem Geany is having?  I've changed the script to save the menu state across Geany restarts.

**Comment by ralf3u** [comment]
> Can you describe the problem Geany is having? I've changed the script to save the menu state across Geany restarts.

OK,  I will do that now.

But meanwhile:
>  ..., did you copy the files from the events folder to ....

I can't find the events folder.

**Comment by xiota** [comment]
> I can't find the events folder.
GeanyLua makes users do a lot on their own.  You have to create any folders that don't exist.  `.config/geany/plugins/geanylua/events`

> The best would be for me that after every restart of Geany the menu-bar is hidden...

I've modified the script again so that you can edit `events/init.lua` to select whether what the script will do on startup.

**Comment by ralf3u** [comment]
What I did in the last minutes:
- I created in .config/geany/plugins/geanylua the file "events"
- in the file "events" I created the document cleanup.lua (I took the content from the webpage)
- in the file "events" I created the document init.lua (I took the content from the webpage)
- I put new code in toggle_menu.lua (I took the content from the webpage) (toggle_menu.lua and hotkeys.cfg are both located in the file .config/geany/plugins/geanylua)

But the issues are still the same, and even worst, because before Geany appears, there is a mistake-window:

![geanylua_mistake_window](https://user-images.githubusercontent.com/68117017/134477115-81efa29b-9ab9-4c0c-9a6a-149a49d82ea0.jpg)

I think that in int.lua is the problem, because after the mistake-window appears, and if I click there on "Open", Geany opens and only init.lua is open.

**Comment by xiota** [comment]
@ralf3u Lua cannot find the file because the name of the script it's looking for is `toggle-menu.lua`, with a dash, not an underscore.

**Comment by ralf3u** [comment]
@xiota Shame on me! I'm sorry for my mistake. Now the two issues mentioned on top of this report do not exist any more.

But if I let appear the menu-bar and then if I close Geany and then reopen Geany, then there is again the menu-bar. Well, I would prefer that Geany starts always with the hidden menu-bar. Would it be possible to add another script to realize this behavior?

**Comment by ralf3u** [comment]
@xiota Shame on me! I'm sorry for my mistake. Now the two issues mentioned on top of this report do not exist any more.

But if I let appear the menu-bar and then if I close Geany and then reopen Geany, then there is again the menu-bar. Well, I would prefer that Geany starts always with the hidden menu-bar. For having this behavior: Can it be that I need only to change in the document ini.lua the lines down below?

action = "startup" to action = "hide"

**Comment by xiota** [comment]
@ralf3u  Changing `action = "startup"` to `action = "hide"` will do what you want.  That is the purpose of that line.

**Comment by ralf3u** [comment]
@xiota Thank you so much for your scripts. It works perfect for me. It is exactly that what I was looking for.

**Comment by xiota** [comment]
@ralf3u Glad it's working for you now.

**Comment by ralf3u** [comment]
@xiota I wanted to share with you a screenshot of my Geany, how beautiful and minimalist it is now:


![geany_minialist](https://user-images.githubusercontent.com/68117017/134825232-3590abf5-4b9f-4f18-b4c4-4823bf727838.jpg)
The image shows the whole window.

**Comment by xiota** [comment]
@ralf3u It's good to know that script is being put to use... Do you really not even have a title bar either?

**Comment by ralf3u** [comment]
@xiota I see no point in using a title-bar. I disabled it in Lubuntu in the document lxqt-rc.xml that is located in .config/openbox. I add 6 lines before the end of the document those lines:

`    <application class="Geany"><decor>no</decor></application>
`

I also changed the color of the unsaved document-name, what you can see in the picture above, because the default color is too strong for me.

**Comment by xiota** [comment]
@ralf3u One of Linux's  strong points is how customizable it is.  I use kde plasma and xfce with the title bar set to hide when windows are maximized.  I keep the title bars n windowed mode because they're familiar and provide a convenient place to grab to move windows around.

**Comment by xiota** [comment]
@ralf3u 

I tend to have most programs maximized.  The main exception is the file manager to drag and drop files into other applications.

> Also Geany can be grabbed without the title-bar by grabbing the menu-bar...

Except that now you have the menu hidden =)

Xfce and plasma both have global menus, so the menu can be hidden and shown elsewhere.
