### ISSUE TITLE
Add one script that contains toggle-menu-bar, auto-sidebar and switch-views

### ISSUE THREAD

**Issue by ralf3u** [xiota/geanylua-scripts#11]
If I build myself a combination of toggle-menu-bar, auto-sidebar and switch-views, then it takes time. And I have to be careful that I don't make a mistake.
So, the idea is to offer on the webpage https://github.com/xiota/geanylua-scripts one script that contains the three scripts. Its name could be:
```
toggle-menu-bar_auto-sidebar_switch-views
```
Then users would need to do only those steps:
- download the zip,
- unzip the file,
- copy the folder `toggle-menu-bar_auto-sidebar_switch-views`,
- paste the copied folder inside the folder `plugins`, and
- rename the pasted folder to `geanylua`.

**Comment by xiota** [comment]
I don't want to combine scripts like that because it's too much effort.

Most scripts should only require combining events and hotkeys files manually.  A couple scripts share functions.

**Comment by ralf3u** [comment]
Well, for me it is not so a problem to create one script that contains toggle-menu-bar, auto-sidebar and switch-views. I can create it in less than five minutes, I think so. Maybe it will not run right away correctly, but after a while I'm sure that I will find where the problem is.
But if I want to publish for users a step-by-step description, then it will be a torture for me and for the users, specially for users who are not used to do this kind of things.

>I don't want to combine scripts like that because it's too much effort.

I can't follow your train of thought.  You just create one script that contains toggle-menu-bar, auto-sidebar and switch-views, then you test it if it works. If it works, you just upload the folder with the name:
```
toggle-menu-bar_auto-sidebar_switch-views
```

**Comment by xiota** [comment]
Adding combination scripts increases the number of files that need to be updated whenever another script is updated.

**Comment by ralf3u** [comment]
>Adding combination scripts increases the number of files that need to be updated whenever another script is updated.

That's true. But in the moment where everything is working perfect, why making changes? And should changes really be made, how many changes there will be within ten years? The scripts are not like the plugin Preview where I can imagine that changes will still be done in the future.

I will test switch-views the next weeks in Lubuntu 24.04. If the three scripts are working perfect then I see a sense in this issue. If you don't want to realize this issue, it's OK, but I think that the decision is not user-friendly. The decision is then developer-friendly.

**Comment by ralf3u** [comment]
>Adding combination scripts increases the number of files that need to be updated whenever another script is updated.

If once you forget to update the script that contains three scripts, then the script will maybe not work, and somebody will open an issue to let you know that there is a trouble. So simple it is.

**Comment by xiota** [comment]
> If once you forget to update the script that contains three scripts, then the script will maybe not work, and somebody will open an issue to let you know that there is a trouble. So simple it is.

That is exactly the scenario I intend to avoid.

You are probably the only person who has or ever will use the auto-sidebar script.  That particular combo is likely to be of use to no one else.  There are currently 57 possible combinations.  I am not going to add any of them.
