### ISSUE TITLE
toggle_menu_bar.lua instead of toggle-menu.lua

### ISSUE THREAD

**Issue by ralf3u** [xiota/geanylua-scripts#2]
I would not call the document 
`toggle-menu.lua`
but
`toggle_menu_bar.lua`
because it is not about the menu, it is about the menu bar.
I would also re-change in all documents menu to menu bar.
So, I would also re-change this:
`toggle_menu-hidden`
to
`toggle_menu_bar-hidden`
Maybe some more words need to be changed, so that the scripts work properly like now.

Remark
If one use `toggle_menu-bar.lua`, then in Preferences, in Keybindings, the hyphen will not appear, so I think it is better to use the underscore, so like this: `toggle_menu_bar.lua`.

**Comment by xiota** [comment]
renamed toggle-menu to toggle-menu-bar.

**Comment by ralf3u** [comment]
I just updated the step-by-step description on https://github.com/geany/geany/issues/633#issuecomment-1030634638.

**Comment by xiota** [comment]
@ralf3u About your question "why not" make a plugin dedicated to hiding the menu bar, I'm not willing to work on it if the Geany devs will just ignore it.
