### ISSUE TITLE
auto-sidebar does not respect "Hide sidebar" during tab-browsing

### ISSUE THREAD

**Issue by ralf3u** [xiota/geanylua-scripts#3]
condition
- for txt-documents: the sidebar does not appear
- for html-documents: the sidebar does appear

issue a)
steps to reproduce
1: put a html-document in focus
2: press shortcut "Hide sidebar" (result: there is no sidebar any more)
3: put a txt-document in focus
4: put back a html-document in focus
result: the sidebar is completely empty
expectation: there should be no sidebar

possible solution
I don't know how to program lua-scripts, but maybe a separate lua-script for the memory could be interesting, to remember if sidebar is disabled.
<br><br><br><br>
REMARK
if the issue above was solved, it could be that the next two following issues will not appear any more

issue b)
steps to reproduce
1: put a html-document in focus
2: press shortcut "Hide sidebar" (result: there is no sidebar any more)
3: put a txt-document in focus
4: put back a html-document in focus
result: the sidebar is completely empty, and the shortcut "Hide sidebar" need to be pressed 3x to let appear again the sidebar
expectation: there should be no sidebar, and by pressing 1x the shortcut "Hide sidebar", the sidebar should appear

issue c)
steps to reproduce
1: put a html-document in focus
2: press shortcut "Hide sidebar" (result: there is no sidebar any more)
3: close Geany
4: reopen Geany
result: the sidebar is completely empty
expectation: there should be no sidebar, and by pressing 1x the shortcut "Hide sidebar", the sidebar should appear

**Comment by ralf3u** [comment]
It seems to be that I did a mistake in the title of the report and in the report. The shortcut name is not `Hide sidebar` but `Toggle sidebar`.

**Comment by xiota** [comment]
Fixed in 615c0c4.  Requires using lua implementation of "toggle sidebar" to create state file.
