### ISSUE TITLE
auto-sidebar.lua does not respect fountain any more

### ISSUE THREAD

**Issue by ralf3u** [xiota/geanylua-scripts#5]
steps to reproduce
just down below the Mardown-line I added this line in auto-sidebar.lua
```
 ["Fountain"] = show_sidebar,
```
I saved the document
I restarted Geany

result
there is no sidebar when a fountain-document is in the editor;
to see the Preview I have to press the shortcut "Toggle Sidebar"

expectation
there should be a sidebar when a fountain-document is in the editor

alternative
I tried also this line
```
 ["FOUNTAIN"] = show_sidebar,
```
and I tried also to put it just before the HTML-line

remark
last year it was working, I think so

remark that does not belong to this issue
last year the font-color was all in white in the Preview, I think so; but now it is black and white; the black part is too hard to read; I tried to change the color in fountain.css; but it didn't work

**Comment by xiota** [comment]
So this worked before because I used to have a patch in the PPA that added fountain document type.  I submitted a PR upstream to include it, but it was ignored.  Geany code changed too much, and the patch no longer works without modification.  Since there wasn't any interest in adding support for fountain and I don't really feel like maintaining a patch no one cares about, I dropped the patch.

I'll take a look at the Lua script to see if there's a workaround to work with fountain documents.

**Comment by ralf3u** [comment]
I see some fountain-documents maybe 5 times a year. For this I can use the shortcut to let appear the sidebar. When reporting, I thought that is was just a small issue that could be fixed easily.

**Comment by ralf3u** [comment]
>remark that does not belong to this issue
last year the font-color was all in white in the Preview, I think so; but now it is black and white; the black part is too hard to read; I tried to change the color in fountain.css; but it didn't work

Is there a solution that I could do that the whole text is white again?

**Comment by ralf3u** [comment]
>Have you already opened an issue for this at [geany-preview](https://github.com/xiota/geany-preview)?

No, I don't think so.

I did https://github.com/xiota/geanylua-scripts/issues/5#issuecomment-1446853464, but there is still no change, what means that some text is in black, and some text is in white.

This is what I did:
I created a document called `filetype_extensions.conf` in `~/.config/geany/filedefs` with this content:
```
[Extensions]
Fountain=*.ftn;*.fountain;
```

Then I copied `/usr/share/geany/filedefs/filetypes.markdown` to `~/.config/geany/filedefs/filetypes.Fountain.conf`.

**Comment by ralf3u** [comment]
>Then copy `/usr/share/geany/filedefs/filetypes.markdown` to `~/.config/geany/filedefs/filetypes.Fountain.conf`.

Are you sure about this line? I ask because there are different formats in the same line.

**Comment by xiota** [comment]
Using `filetypes.markdown` as a template for `filetypes.Fountain.conf`.  Otherwise, you would need to create the new file from scratch.

**Comment by ralf3u** [comment]
I did https://github.com/xiota/geanylua-scripts/issues/5#issuecomment-1446853464.
At the moment in my geanylua-file there is only the old version of auto-sidebar. But auto-sidebar still does not respect fountain.

**Comment by ralf3u** [comment]
Sorry for my last comment. I forgot to do this:
In  `auto-sidebar.lua` I just added this line in the section `local action_tbl`, like it is mentioned in the report, on top of this webpage:
```
 ["Fountain"] = show_sidebar,
```
Now it works.

**Comment by xiota** [comment]
When you get a chance, try the new auto-sidebar.  It respects the sidebar state (issue #3) when used with the `toggle-sidebar` script.  It shares some files with `switch-views` and uses `sidebar_restore` in `action_tbl`.

**Comment by ralf3u** [comment]
>When you get a chance, try the new auto-sidebar. ...

Yes, this is what I wanted to do the next days.
