### ISSUE TITLE
One additional shortcut for Geany Preview: Toggle sidebar visibility+focus

### ISSUE THREAD

**Issue by ralf3u** [xiota/geanylua-scripts#8]
If one day the focus problem will be solved in Geany Preview (see also https://github.com/xiota/geany-preview/issues/5 and https://github.com/xiota/geany-preview/issues/15), there is one shortcut that could be added to the shortcuts in Geany Preview. Instead of
`Toggle sidebar visibility`
there could be two shortcuts with this kind of names:
`Toggle sidebar visibility+focus` and
`Toggle sidebar visibility; focus stays in the editor`.

This report is based on #7.
This suggestion for improvement was mentioned for the first time on https://github.com/xiota/geany-preview/issues/38#issuecomment-1445172438.

**Comment by xiota** [comment]
The problem is `geany.activate()` is not working.  I have looked at the GeanyLua plugin code and don't see why it doesn't work.  I have already opened a bug report upstream.

**Comment by ralf3u** [comment]
To the time where I opened the issue it was not clear if the focus feature could be solved. Now where it is clear that a solution is possible, there is no need for this issue any more. The solution for this issue will be continued on #7.
